openapi: 3.2.0
info:
  title: True Fit - Consumer Style Attributes API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Style Attributes
  description: The style attributes available for particular ageGroup, gender, category and optional class combination.
paths:
  /style-attributes:
    get:
      tags:
      - Style Attributes
      summary: Retrieve available style attributes for the given category, ageGroup, gender…
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: category
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Bottoms
          - Dresses
          - Tops
          - Shoes
          - Bras
      - name: ageGroup
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      - name: gender
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Female
          - Male
          - Unisex
      - name: classification
        in: query
        description: An optional class paremeter retrieved from the /brands/{brandId}/classes endpoint.
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: The retrieved style attributes.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/AvailableStyleAttributes'
      operationId: getStyleAttributes
      x-operation-id-source: derived
components:
  schemas:
    AvailableStyleAttributes:
      type: object
      properties:
        styleType:
          type: string
          enum:
          - WomensBraBandFit
          - WomensBraCupFit
          - WomensBraStyle
          - WomensSilhouette
          - WomensTopsStyle
          - WomensSleeveLength
          - WomensBottomsStyle
          - WomensRise
          - MensPantsFit
          - MensBottomsStyle
          - ClosetItemAge
          - FitDescription
        values:
          type: array
          items:
            type: string
x-explorer-enabled: false
