openapi: 3.2.0
info:
  title: True Fit - Consumer Sizes API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Sizes
  description: The sizes that are available to choose from when entering a reference closet item.
paths:
  /sizes:
    get:
      tags:
      - Sizes
      summary: Retrieve the available sizes for the given combination of brandId, category…
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: category
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Bottoms
          - Dresses
          - Tops
          - Shoes
          - Bras
      - name: gender
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Female
          - Male
          - Unisex
      - name: ageGroup
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      - name: locale
        in: query
        description: 'Identifier specifying the locale to use when retrieving suggested brands or any type of sizes e.g. sizes, bra sizes, inseams or sleeve lengths. This attribute is only required when the store supports multiple locales. Use an ISO 639 language code followed by an ISO 3166 country code, e.g. en_US. '
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: brandId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: The sizes for the given combination of brandId, category, gender, and age group.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Size'
      operationId: getSizes
      x-operation-id-source: derived
  /sizes/{sizeId}:
    get:
      tags:
      - Sizes
      summary: Retrieve the size object based on a sizeId
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: sizeId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: The size object based on a sizeId.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Size'
              example:
                id: string
                label: string
                localeCode: string
                secondLabel: string
                sizeType: Regular
                system: string
      operationId: getSizesBySizeId
      x-operation-id-source: derived
components:
  schemas:
    SizeGroup:
      type: string
      description: The optional group the size belongs to. This is used only for display purposes. This can be either `Kids` or `LittleKids`
      example: Kids
      enum:
      - Kids
      - LittleKids
    Size:
      required:
      - id
      - label
      - localeCode
      - sizeType
      - system
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        localeCode:
          type: string
        secondLabel:
          type: string
        sizeType:
          $ref: '#/components/schemas/SizeType'
        system:
          type: string
        isTypicalSecondSize:
          type: boolean
        sizeGroup:
          $ref: '#/components/schemas/SizeGroup'
    SizeType:
      type: string
      example: Regular
      enum:
      - BigAndTall
      - Juniors
      - Misses
      - Petite
      - Plus
      - Regular
      - Tall
      - Husky
      - Slim
      - Unisex
x-explorer-enabled: false
