openapi: 3.2.0
info:
  title: True Fit - Consumer Brands API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Brands
  description: The brands that are available to choose from when entering a reference closet item.
paths:
  /brands:
    get:
      tags:
      - Brands
      summary: Retrieve the available brands for the given combination of category, gender…
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: category
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Bottoms
          - Dresses
          - Tops
          - Shoes
          - Bras
      - name: gender
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Female
          - Male
          - Unisex
      - name: ageGroup
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      responses:
        '200':
          description: The brands for the given combination of category, gender, and age group.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
      operationId: getBrands
      x-operation-id-source: derived
  /brands/{brandId}:
    get:
      tags:
      - Brands
      summary: Retrieve the brand object based on a brandId
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: brandId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: The brand object based on a brandId.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Brand'
        '404':
          description: Not Found
      operationId: getBrandsByBrandId
      x-operation-id-source: derived
  /brands/suggested:
    get:
      tags:
      - Brands
      summary: Retrieve the suggested brands for the given combination of category, gender…
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: category
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Bottoms
          - Dresses
          - Tops
          - Shoes
          - Bras
      - name: gender
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Female
          - Male
          - Unisex
      - name: ageGroup
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      - name: locale
        in: query
        description: 'Identifier specifying the locale to use when retrieving suggested brands or any type of sizes e.g. sizes, bra sizes, inseams or sleeve lengths. This attribute is only required when the store supports multiple locales. Use an ISO 639 language code followed by an ISO 3166 country code, e.g. en_US. '
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: age
        in: query
        description: Specify to retrieve suggestions for this target age (in years).
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: limit
        in: query
        description: The max count of brands to return.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      responses:
        '200':
          description: The suggested brands for the given combination of category, gender, and age group.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Brand'
      operationId: getBrandsSuggested
      x-operation-id-source: derived
  /brands/{brandId}/styles:
    get:
      tags:
      - Brands
      summary: Retrieve the brand styles for the brand, category, gender, and age group
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: category
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Bottoms
          - Dresses
          - Tops
          - Shoes
          - Bras
      - name: gender
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Female
          - Male
          - Unisex
      - name: ageGroup
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      - name: brandId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: The brand styles for the brand, category, gender, and age group.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/BrandStyle'
      operationId: getBrandsByBrandIdStyles
      x-operation-id-source: derived
  /brands/{brandId}/styles/{brandStyleId}:
    get:
      tags:
      - Brands
      summary: Retrieve the brand style object for the brand style id
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: brandId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: brandStyleId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: Brand style object based on the given id.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BrandStyle'
        '404':
          description: Not Found
      operationId: getBrandsByBrandIdStylesByBrandStyleId
      x-operation-id-source: derived
  /brands/{brandId}/classes:
    get:
      tags:
      - Brands
      summary: Retrieve the classes for the brand, category, gender, and age group
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: category
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Bottoms
          - Dresses
          - Tops
          - Shoes
          - Bras
      - name: gender
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Female
          - Male
          - Unisex
      - name: ageGroup
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      - name: brandId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: The classes for the brand, category, gender, and age group.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                example:
                - AthleticSneakers
                - Flats
                - Heels
                - Sandals
                - Boots
                items:
                  $ref: '#/components/schemas/Classification'
      operationId: getBrandsByBrandIdClasses
      x-operation-id-source: derived
components:
  schemas:
    Classification:
      type: string
      description: "###### Possible Mens Shoes Classifications\n* AthleticSneakers\n* Casual \n* Dress\n* Sandals\n* Boots\n###### Possible Womens Shoes Classifications\n* AthleticSneakers\n* Flats\n* Sandals\n* Boots\n* Heels\n"
      example: General
      enum:
      - AthleticSneakers
      - Boots
      - Casual
      - CasualShirts
      - Dress
      - DressShirts
      - Flats
      - General
      - Heels
      - Jeans
      - Pants
      - Sandals
    Brand:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        aliases:
          type: array
          description: 'These are other names the brand goes by that aren''t name. This field can be used to drive any typeahead searches for brands

            '
          items:
            type: string
      example:
        id: brand123
        name: 7 For All Mankind
        aliases:
        - Seven for all mankind
        - 7forallmankind
    BrandStyle:
      required:
      - id
      - name
      type: object
      properties:
        id:
          type: string
        name:
          type: string
      example:
        id: brandstyle123
        name: Cool Jeans
x-explorer-enabled: false
