openapi: 3.2.0
info:
  title: True Fit - Consumer Normalized Sizes API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Normalized Sizes
  description: Retrieve normalized sizes for the shopper profile.
paths:
  /normalized-sizes:
    get:
      tags:
      - Normalized Sizes
      summary: Retrieve normalized sizes for the shopper profile
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: profileId
        in: query
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: merchantCategoryId
        in: query
        description: Numeric category ID.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: gender
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Male
          - Female
          - Unisex
      - name: ageGroup
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      responses:
        '200':
          description: Normalized sizes were successfully returned.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NormalizedSizesResultSet'
        '400':
          description: Required parameter 'profileId' not found.
        '404':
          description: Profile not found.
      operationId: getNormalizedSizes
      x-operation-id-source: derived
  /normalized-sizes/recommendable:
    get:
      tags:
      - Normalized Sizes
      summary: Determine if provided category is recommendable
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: profileId
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: merchantCategoryId
        in: query
        description: Numeric category ID.
        required: false
        style: form
        explode: true
        schema:
          type: integer
      - name: gender
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Male
          - Female
          - Unisex
      - name: ageGroup
        in: query
        required: false
        style: form
        explode: true
        schema:
          type: string
          enum:
          - Adult
          - Child
      responses:
        '200':
          description: The recommendability status returned successfully
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/text:
              schema:
                type: boolean
      operationId: getNormalizedSizesRecommendable
      x-operation-id-source: derived
components:
  schemas:
    NormalizedSizesResultSet:
      required:
      - normalizedSizes
      - status
      - supportedSizeTypes
      type: object
      properties:
        status:
          type: string
          description: If the status is estimationinprogress, a refreshAfter should also come back on the NormalizedSizesResultSet, and another call for a  normalized sizes should be made after the refreshAfter delay.
          enum:
          - success
          - estimationinprogress
          - incompleteprofile
          - unrecommendabledepartment
          - invaliddepartment
          - error
        normalizedSizes:
          type: array
          items:
            $ref: '#/components/schemas/NormalizedSize'
        supportedSizeTypes:
          type: array
          items:
            $ref: '#/components/schemas/SupportedSizeTypes'
        refreshAfter:
          type: integer
          description: If we can't provide the normalized sizes at the moment, the amount of time in milliseconds to wait before trying to retrieve a recommendation again.
    NormalizedSize:
      required:
      - merchantCategoryId
      - normalizedSizes
      type: object
      properties:
        merchantCategoryId:
          type: integer
        gender:
          type: string
        ageGroup:
          type: string
        normalizedSize:
          type: integer
          description: Normalized size corresponding to the merchantCategoryId.
    SupportedSizeTypes:
      required:
      - merchantCategoryId
      - supportedSizeTypes
      type: object
      properties:
        merchantCategoryId:
          type: integer
        gender:
          type: string
        ageGroup:
          type: string
        supportedSizeTypes:
          type: integer
          description: Supported size types bitmap corresponding to the merchantCategoryId
x-explorer-enabled: false
