openapi: 3.2.0
info:
  title: True Fit - Consumer Inseams API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Inseams
  description: The available inseam lengths to choose from for the inseam measurement on a profile.
paths:
  /inseams:
    get:
      tags:
      - Inseams
      summary: Retrieve the available inseam lengths
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: locale
        in: query
        description: 'Identifier specifying the locale to use when retrieving suggested brands or any type of sizes e.g. sizes, bra sizes, inseams or sleeve lengths. This attribute is only required when the store supports multiple locales. Use an ISO 639 language code followed by an ISO 3166 country code, e.g. en_US. '
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: All available inseam length values. The `uom` field will contain the unit of measure, and the `values` field will contain all available values in display order.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                example:
                - uom: In
                  values:
                  - 30
                  - 31
                  - 32
                - uom: Cm
                  values:
                  - 70
                  - 71
                  - 72
                items:
                  $ref: '#/components/schemas/AvailableLengths'
      operationId: getInseams
      x-operation-id-source: derived
components:
  schemas:
    AvailableLengths:
      type: object
      properties:
        uom:
          type: string
          enum:
          - In
          - Cm
        values:
          type: array
          items:
            type: integer
x-explorer-enabled: false
