openapi: 3.2.0
info:
  title: True Fit - Consumer Product Ratings API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Product Ratings
  description: An endpoint for rating discovery recommendations.
paths:
  /profiles/{profileId}/product-ratings:
    get:
      tags:
      - Product Ratings
      summary: Get all product ratings for the user
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: profileId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: The product ratings for the user.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserProductRating'
        '404':
          description: 'The profileId in the path does not exist.

            '
      operationId: getProfilesByProfileIdProductRatings
      x-operation-id-source: derived
    post:
      tags:
      - Product Ratings
      summary: Save the user's product rating
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: profileId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProductRating'
        required: true
      responses:
        '200':
          description: The user's product rating was successfully saved.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProductRating'
        '400':
          description: The user's product rating was not successfully saved because of an invalid UserProductRating. This could include invalid styleId/colorId combinations, and invalid ratings.
      operationId: postProfilesByProfileIdProductRatings
      x-operation-id-source: derived
  /profiles/{profileId}/product-ratings/{productRatingId}:
    put:
      tags:
      - Product Ratings
      summary: Update the user's product rating
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: profileId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: productRatingId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserProductRating'
        required: true
      responses:
        '200':
          description: The user's product rating was successfully saved.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserProductRating'
        '400':
          description: The user's product rating was not successfully saved because of an invalid UserProductRating or productRatingId, or the productRatingId was missing.
        '404':
          description: The user's product rating was not successfully saved because it does not exist for the profile.
      operationId: putProfilesByProfileIdProductRatingsByProductRatingId
      x-operation-id-source: derived
    delete:
      tags:
      - Product Ratings
      summary: Deletes a user's product rating
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: profileId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: productRatingId
        in: path
        required: true
        style: simple
        explode: false
        schema:
          type: string
      responses:
        '200':
          description: The user's product rating was successfully deleted.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
        '400':
          description: The user's product rating was not successfully deleted because of an invalid productRatingId.
        '404':
          description: The user's product rating was not successfully deleted because it does not exist for the profile.
      operationId: deleteProfilesByProfileIdProductRatingsByProductRatingId
      x-operation-id-source: derived
components:
  schemas:
    ProductRating:
      type: string
      example: Like
      enum:
      - Like
      - Dislike
    UserProductRating:
      required:
      - id
      - rating
      - styleId
      type: object
      properties:
        id:
          type: string
          description: This field is populated by the server, never created by the client.
          readOnly: true
          example: someUserProductRatingId
        styleId:
          type: string
        colorId:
          type: string
        rating:
          $ref: '#/components/schemas/ProductRating'
x-explorer-enabled: false
