openapi: 3.2.0
info:
  title: True Fit - Consumer Analytics API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Analytics
  description: Provide session information for more advanced reporting.
paths:
  /analytics/tracking:
    post:
      tags:
      - Analytics
      summary: Send session information to True Fit for more advanced reporting
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: locale
        in: query
        description: 'Identifier specifying the locale to use when retrieving suggested brands or any type of sizes e.g. sizes, bra sizes, inseams or sleeve lengths. This attribute is only required when the store supports multiple locales. Use an ISO 639 language code followed by an ISO 3166 country code, e.g. en_US. '
        required: false
        style: form
        explode: true
        schema:
          type: string
      - name: X-TF-StoreUserId
        in: header
        description: The store user id for the current user.
        required: false
        style: simple
        explode: false
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Tracking'
      responses:
        '201':
          description: Successfully logged
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
      operationId: postAnalyticsTracking
      x-operation-id-source: derived
components:
  schemas:
    DeviceType:
      type: string
      enum:
      - desktop
      - mobile
    IntegrationPlatform:
      type: string
      enum:
      - web
      - app
    Tracking:
      type: object
      properties:
        referrerUri:
          type: string
          description: The URI of the page that linked to this page.
          example: www.google.com
        deviceType:
          $ref: '#/components/schemas/DeviceType'
        integrationPlatform:
          $ref: '#/components/schemas/IntegrationPlatform'
        widgetHidden:
          type: boolean
          description: True Fit A/B test group identifier. true if control group and false if True Fit group.
          example: false
        storeExperimentKey:
          type: string
          description: Identifier of any test group user is which the user is included.
          example: control
x-explorer-enabled: false
