openapi: 3.2.0
info:
  title: True Fit - Consumer Bra Sizes API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Bra Sizes
  description: The bra sizes that are available to choose from for the bra size measurement on a Women's profile.
paths:
  /bra-sizes:
    get:
      tags:
      - Bra Sizes
      summary: Retrieve the available bra sizes
      parameters:
      - name: X-TF-UserToken
        in: header
        description: The session token for the current user.
        required: true
        style: simple
        explode: false
        schema:
          type: string
      - name: locale
        in: query
        description: 'Identifier specifying the locale to use when retrieving suggested brands or any type of sizes e.g. sizes, bra sizes, inseams or sleeve lengths. This attribute is only required when the store supports multiple locales. Use an ISO 639 language code followed by an ISO 3166 country code, e.g. en_US. '
        required: false
        style: form
        explode: true
        schema:
          type: string
      responses:
        '200':
          description: The available generic bra sizes. The `label` field will contain band sizes, and the `secondLabel` field will contain cup sizes.
          headers:
            X-TF-UserToken:
              description: The updated token for the user. This updated token should be used on all following requests. This header is only present when the token has cycled.
              style: simple
              explode: false
              schema:
                type: string
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Size'
      operationId: getBraSizes
      x-operation-id-source: derived
components:
  schemas:
    SizeGroup:
      type: string
      description: The optional group the size belongs to. This is used only for display purposes. This can be either `Kids` or `LittleKids`
      example: Kids
      enum:
      - Kids
      - LittleKids
    Size:
      required:
      - id
      - label
      - localeCode
      - sizeType
      - system
      type: object
      properties:
        id:
          type: string
        label:
          type: string
        localeCode:
          type: string
        secondLabel:
          type: string
        sizeType:
          $ref: '#/components/schemas/SizeType'
        system:
          type: string
        isTypicalSecondSize:
          type: boolean
        sizeGroup:
          $ref: '#/components/schemas/SizeGroup'
    SizeType:
      type: string
      example: Regular
      enum:
      - BigAndTall
      - Juniors
      - Misses
      - Petite
      - Plus
      - Regular
      - Tall
      - Husky
      - Slim
      - Unisex
x-explorer-enabled: false
