openapi: 3.2.0
info:
  title: True Fit - Consumer Token API
  description: These APIs can be used to create a custom True Fit integration.
  version: '3.0'
servers:
- url: /profile/public/v3/{tla}
tags:
- name: Token
  description: A token is used to identify requests from a device and associate the requests with a session. As the user interacts with True Fit, the token will update. The most recent token returned by True Fit should be used on subsequent requests.
paths:
  /token:
    get:
      tags:
      - Token
      summary: Get a new user session token, or reflect the current one if a valid token…
      responses:
        '200':
          description: token returned
          headers:
            X-TF-UserTokenMaxAge:
              description: This will be most useful when storing the token as a cookie. The value is the suggested max age of the token (in seconds).
              style: simple
              explode: false
              schema:
                type: integer
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
      operationId: getToken
      x-operation-id-source: derived
components:
  schemas:
    inline_response_200:
      type: object
      properties:
        token:
          type: string
      example:
        token: 134232023kfjho2022075
x-explorer-enabled: false
